constr:
  TestConstr:
  MCell:
    drawBorder: true
    argNum: 2
  MListSeg:
    inPort: list
    args:
      0:
        forceEdge: true # forceEdge=true means there is always an edge to this argument
        outPort: list
      1:
        inTable: true
        inPort: list
        outPort: list
  MList:
    argNum: 1
  MQueue:
    args:
      0:
        inTable: true
  MNode:
    drawBorder: true
    argNum: 3
  MTree:
    args:
      0:
        inTable: true
  MCell2:
    drawBorder: true
    argNum: 2
  # slf Repr.html
  Record2:
    drawBorder: true
    argNum: 4
    args:
      0:
        inTable: false
      2:
        inTable: false
  Record2':
    drawBorder: true
    argNum: 4
    args:
      0:
        inTable: false
      2:
        inTable: false
  Record3:
    drawBorder: true
    argNum: 6
    args:
      0:
        inTable: false
      2:
        inTable: false
      4:
        inTable: false
  Record3':
    drawBorder: true
    argNum: 6
    args:
      0:
        inTable: false
      2:
        inTable: false
      4:
        inTable: false
  Stack:
    argNum: 1
  SingleCell:
    drawBorder: true
    argNum: 1
  # iris-tutorial queue
  isQueue:
    argNum: 1
